MOUSEKEY_ENABLE = no     # Mouse keys
VIA_ENABLE      = yes    # Enable VIA
LTO_ENABLE      = yes

GRAVE_ESC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
